version: 2

sphinx:
  configuration: docs/conf.py

formats: all

python:
  install:
    - method: pip
      path: "."

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

submodules:
  include: all